#!/bin/bash
# Read access to transformer/terraform-cloud/terraform.tfvars (sourced; needs
# tools.sh and TFVARS to be set). The file is converted once with hcl2json and
# cached for the life of the process.

_TFVARS_JSON=""
_TFVARS_JSON_FOR=""

# tfvars_json — the whole tfvars file as JSON (empty object when missing).
tfvars_json() {
  if [ -z "$_TFVARS_JSON" ] || [ "$_TFVARS_JSON_FOR" != "$TFVARS" ]; then
    if [ -f "$TFVARS" ]; then
      _TFVARS_JSON="$("$(sg_resolve hcl2json sg_ensure_hcl2json)" "$TFVARS" 2>/dev/null || echo '{}')"
    else
      _TFVARS_JSON='{}'
    fi
    _TFVARS_JSON_FOR="$TFVARS"
  fi
  printf '%s' "$_TFVARS_JSON"
}

# tfvars_get <jq-expr> [default] — raw value of an expression over the tfvars
# JSON, e.g. tfvars_get '.tfOrg'. Prints the default when null/missing.
tfvars_get() {
  local expr="$1" def="${2-}" v
  v="$(tfvars_json | "$(sg_resolve jq sg_ensure_jq)" -r "$expr // empty" 2>/dev/null || true)"
  printf '%s' "${v:-$def}"
}

# tfvars_get_json <jq-expr> — compact JSON value of an expression (or null).
tfvars_get_json() {
  tfvars_json | "$(sg_resolve jq sg_ensure_jq)" -c "$1 // null" 2>/dev/null || echo null
}

# tfvars_has <key> — exit 0 when the top-level key is present in the file (an
# explicit `key = null` counts as present; a missing key means the variable's
# default applies).
tfvars_has() {
  tfvars_json | "$(sg_resolve jq sg_ensure_jq)" -e --arg k "$1" 'has($k)' >/dev/null 2>&1
}

# tfvars_is_null <key> — exit 0 when the file sets the key to null explicitly.
tfvars_is_null() {
  tfvars_has "$1" && [ "$(tfvars_get_json ".$1")" = "null" ]
}

# tfvars_invalidate — forget the cached conversion (after writing the file).
tfvars_invalidate() { _TFVARS_JSON=""; }

# tfvars_valid — exit 0 when the file exists and hcl2json can parse it;
# the parser's message is printed on stdout otherwise.
tfvars_valid() {
  [ -f "$TFVARS" ] || return 1
  # shellcheck disable=SC2069  # stderr is the result; stdout (the JSON) is discarded
  "$(sg_resolve hcl2json sg_ensure_hcl2json)" "$TFVARS" 2>&1 >/dev/null
}

# _tfvars_hcl <json> — pretty-print a JSON value so it reads like HCL in the file.
_tfvars_hcl() { printf '%s' "$1" | "$(sg_resolve jq sg_ensure_jq)" --indent 2 '.' 2>/dev/null || printf '%s' "$1"; }

# _tfvars_str <text> — a quoted HCL string literal (backslashes, quotes and
# template sequences escaped, so any connector or org name round-trips).
_tfvars_str() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//\$\{/\$\$\{}"
  s="${s//%\{/%%\{}"
  printf '"%s"' "$s"
}

# tfvars_write <dest> — render terraform.tfvars from W_* variables set by the
# wizard (lists/objects are passed as compact JSON, which HCL accepts). Keeps
# the same order and comments as terraform.tfvars.example so the file stays
# hand-editable afterwards.
#   W_TFORG W_TFHOST W_WSNAMES_JSON W_TAGS_JSON W_IGNORE_TAGS_JSON W_EXPORT_STATE
#   W_APPROVERS_JSON W_REPO_PREFIX W_VCS_INTEGRATION W_DPC_JSON W_RUNNER_JSON
#   W_DEST_KIND W_TF_SOURCE W_TF_VERSION W_TRIGGERS W_IGNORE_PATTERNS_JSON
# W_RUNNER_JSON and W_TF_VERSION may be the literal "null" (defer to the org's
# execution preset).
tfvars_write() {
  local dest="$1" host_line="" tf_version_hcl
  if [ "${W_TF_VERSION:-null}" = "null" ]; then tf_version_hcl="null"; else tf_version_hcl="$(_tfvars_str "$W_TF_VERSION")"; fi
  if [ "${W_TFHOST:-app.terraform.io}" != "app.terraform.io" ]; then
    host_line="$(printf '\n# Terraform Enterprise hostname (omit for Terraform Cloud)\ntfHostname = %s\n' "$(_tfvars_str "$W_TFHOST")")"
  fi
  cat >"$dest" <<TFVARS
# Generated by 'sg-migrate.sh init' on $(date -u +%Y-%m-%dT%H:%M:%SZ). Safe to edit by hand;
# re-run 'sg-migrate.sh init' to go through the wizard again.

# Terraform Cloud/Enterprise organization name
tfOrg = $(_tfvars_str "$W_TFORG")
$host_line
# List of workspace names to export. Use wildcards (e.g., ["*"]) for all workspaces
workspacenames = $W_WSNAMES_JSON

# Export Terraform state
exportStateFiles = $W_EXPORT_STATE

# Only include workspaces carrying these tags (null = all)
tfWorkspaceTags = $W_TAGS_JSON

# Exclude workspaces carrying these tags (null = none). Excludes win over includes.
tfWorkspaceIgnoreTags = $W_IGNORE_TAGS_JSON

# Directory to export Terraform files to
exportPath = "export"

# TFC/TFE-specific variables that are not migrated (regexes on the variable
# name), e.g. TFC_WORKSPACE_NAME or TFC_AWS_RUN_ROLE_ARN. [] keeps everything.
ignoreVarPatterns = $W_IGNORE_PATTERNS_JSON

# Emails of the users who must approve plans (approvalPreApply is set for
# workspaces without auto-apply)
SGDefaultWfApprovers = $W_APPROVERS_JSON

# Prefix for your repo URL
SGDefaultIACVCSRepoPrefix = $(_tfvars_str "$W_REPO_PREFIX")

# VCS connector used to clone the repositories (/integrations/<name>)
SGDefaultVCSAuthIntegrationID = $(_tfvars_str "$W_VCS_INTEGRATION")

# Cloud connector the workflows deploy with
SGDefaultDeploymentPlatformConfig = $(_tfvars_hcl "$W_DPC_JSON")

# Runners for every workflow: { type = "shared" } for SG-hosted runners,
# { type = "private", names = ["<runner-group>"] } for a private runner group, or
# null to let the org's execution preset decide (Settings -> Runner groups).
SGDefaultRunnerConstraints = $(_tfvars_hcl "${W_RUNNER_JSON:-null}")

# Choose from: GITHUB_COM, BITBUCKET_ORG, GITLAB_COM, AZURE_DEVOPS, GIT_OTHER
SGDefaultSourceConfigDestKind = $(_tfvars_str "$W_DEST_KIND")

# Where the workflows get their Terraform version from: "carry" keeps each
# workspace's pinned TFC version (the fallback below covers the rest); "preset"
# sends no version, so the org's execution preset applies.
SGTerraformVersionSource = $(_tfvars_str "${W_TF_SOURCE:-carry}")

# Fallback for "carry": SG Terraform version used when a workspace's version is
# not a pinned semver, or when the SG API rejects a pinned version as above the
# managed ceiling (1.5.7, the last MPL/FOSS release; newer versions are BSL and
# not bundled). null = leave those workflows to the org's execution preset.
SGDefaultTerraformVersion = $tf_version_hcl

# Pre-configure VCS triggers on each workflow from the workspace's TFC settings
SGDefaultEnableVCSTriggers = $W_TRIGGERS

# Re-pull state for every workspace on each apply (default: idempotent)
forceStateRefresh = false

# Per-workspace overrides, keyed by workspace name. Any field set here wins over
# the SGDefault* value above, for that workspace only. See terraform.tfvars.example
# for every supported field.
# workspaceOverrides = {
#   "prod-networking" = {
#     RunnerConstraints = { "type" : "private", "names" : ["sg-runner"] }
#     Approvers         = ["lead@example.com"]
#     terraformVersion  = "TERRAFORM-1.5.7"
#   }
# }
TFVARS
  tfvars_invalidate
}
